site_name: Astral Wiki
nav:
    - 主页: "index.md"
    - 搭建指南-星骰: 
      - "前言": "1.md"
      - "基础搭建（手机）": "1-1.md"
    - 基础功能-星骰: 
      - "基础功能": "function.md"
      - "基础指令": "directives.md"
      - "文件载入": "load.md"
      - "自定义帮助": "about.md"
    - 进阶功能-星骰:
      - "牌堆": "draw.md"
      - "基础自定义（回雪）": "class.md"
      - "进阶自定义（JS和LUA）": "js-lua.md"
      - "房规": "rules.md"
      - "Mirai码": "mirai.md"
    - 非文本相关:
      - "特殊函数": "special-functions.md"
      - "mirai码": "mirai.md"
      - "CQ码": "cq.md"
    - 其他教程:
      - "MT管理器教学": "MT.md"
      - "提问的艺术": "askingarts.md"
    - API:
      - "Astral论坛相关API": "api.md"
      - "星骰api": "astralapi.md"
    - 论坛: "https://astral.snoweven.com/"
    
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.top
    - navigation.footer
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - css/custom.css
  - css/extra.css
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde